import 'models.dart';

final sampleWorkoutPlans = [
  WorkoutPlan(
    id: 'fbw-beginner',
    name: 'FBW Beginner',
    description: 'Plan startowy całego ciała, 3 dni treningowe w tygodniu.',
    days: [
      WorkoutDay(
        id: 'fbw-beginner-a',
        name: 'A',
        focus: 'Całe ciało - technika i baza siłowa',
        lastCompletedLabel: 'Ostatni trening 12.06.2026',
        exercises: [
          Exercise(
            id: 'goblet-squat',
            name: 'Goblet squat',
            description: 'Kontrolowany przysiad z hantlem trzymanym przed klatką.',
            sets: 4,
            targetRir: 2,
            restSeconds: 120,
            currentWeightKg: 20,
            currentTargetReps: 12,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 8,
              maxReps: 12,
              repStep: 1,
              weightIncrementKg: 2.5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'goblet-squat',
              completedAt: DateTime(2026, 6, 12),
              weightKg: 20,
              reps: 11,
              rir: 2,
            ),
          ),
          Exercise(
            id: 'bench-press',
            name: 'Wyciskanie na ławce',
            description: 'Prowadź sztangę stabilnie i zostaw zapas zgodny z RIR.',
            sets: 4,
            targetRir: 1,
            restSeconds: 150,
            currentWeightKg: 40,
            currentTargetReps: 10,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 8,
              maxReps: 12,
              repStep: 1,
              weightIncrementKg: 5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'bench-press',
              completedAt: DateTime(2026, 6, 12),
              weightKg: 40,
              reps: 9,
              rir: 1,
            ),
          ),
          Exercise(
            id: 'seated-row',
            name: 'Wiosłowanie siedząc',
            description: 'Ściągaj łopatki i utrzymuj neutralny kręgosłup.',
            sets: 4,
            targetRir: 1,
            restSeconds: 120,
            currentWeightKg: 20,
            currentTargetReps: 18,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 12,
              maxReps: 18,
              repStep: 2,
              weightIncrementKg: 2.5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'seated-row',
              completedAt: DateTime(2026, 6, 12),
              weightKg: 20,
              reps: 17,
              rir: 1,
            ),
          ),
        ],
      ),
      WorkoutDay(
        id: 'fbw-beginner-b',
        name: 'B',
        focus: 'Plecy, nogi i stabilizacja',
        lastCompletedLabel: 'Ostatni trening 14.06.2026',
        exercises: [
          Exercise(
            id: 'romanian-deadlift',
            name: 'Martwy ciąg rumuński',
            description: 'Ruch biodrami w tył, napięty brzuch i spokojne tempo.',
            sets: 4,
            targetRir: 2,
            restSeconds: 150,
            currentWeightKg: 50,
            currentTargetReps: 8,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 8,
              maxReps: 12,
              repStep: 1,
              weightIncrementKg: 5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'romanian-deadlift',
              completedAt: DateTime(2026, 6, 14),
              weightKg: 50,
              reps: 8,
              rir: 2,
            ),
          ),
          Exercise(
            id: 'lat-pulldown',
            name: 'Ściąganie drążka',
            description: 'Prowadź łokcie w dół i kontroluj powrót ciężaru.',
            sets: 4,
            targetRir: 1,
            restSeconds: 120,
            currentWeightKg: 35,
            currentTargetReps: 14,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 10,
              maxReps: 16,
              repStep: 2,
              weightIncrementKg: 2.5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'lat-pulldown',
              completedAt: DateTime(2026, 6, 14),
              weightKg: 35,
              reps: 12,
              rir: 1,
            ),
          ),
          Exercise(
            id: 'overhead-press',
            name: 'Wyciskanie nad głowę',
            description: 'Napnij pośladki i prowadź ciężar blisko środka ciała.',
            sets: 3,
            targetRir: 2,
            restSeconds: 120,
            currentWeightKg: 25,
            currentTargetReps: 8,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 8,
              maxReps: 12,
              repStep: 1,
              weightIncrementKg: 2.5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'overhead-press',
              completedAt: DateTime(2026, 6, 14),
              weightKg: 25,
              reps: 7,
              rir: 2,
            ),
          ),
        ],
      ),
      WorkoutDay(
        id: 'fbw-beginner-c',
        name: 'C',
        focus: 'Objętość, hantle i akcesoria',
        lastCompletedLabel: 'Ostatni trening 16.06.2026',
        exercises: [
          Exercise(
            id: 'leg-press',
            name: 'Wypychanie na suwnicy',
            description: 'Pełna kontrola ruchu, bez blokowania kolan na górze.',
            sets: 4,
            targetRir: 1,
            restSeconds: 150,
            currentWeightKg: 80,
            currentTargetReps: 12,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 10,
              maxReps: 15,
              repStep: 1,
              weightIncrementKg: 5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'leg-press',
              completedAt: DateTime(2026, 6, 16),
              weightKg: 80,
              reps: 12,
              rir: 1,
            ),
          ),
          Exercise(
            id: 'incline-dumbbell-press',
            name: 'Wyciskanie hantli skos',
            description: 'Utrzymaj stabilne łopatki i równą pracę obu ramion.',
            sets: 4,
            targetRir: 1,
            restSeconds: 120,
            currentWeightKg: 20,
            currentTargetReps: 10,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 8,
              maxReps: 12,
              repStep: 1,
              weightIncrementKg: 2.5,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'incline-dumbbell-press',
              completedAt: DateTime(2026, 6, 16),
              weightKg: 20,
              reps: 10,
              rir: 1,
            ),
          ),
          Exercise(
            id: 'face-pull',
            name: 'Face pull',
            description: 'Prowadź linkę w stronę twarzy i mocno pracuj tyłem barku.',
            sets: 3,
            targetRir: 2,
            restSeconds: 90,
            currentWeightKg: 12,
            currentTargetReps: 16,
            progressionRule: ProgressionRule(
              type: ProgressionType.doubleProgression,
              minReps: 12,
              maxReps: 20,
              repStep: 2,
              weightIncrementKg: 1,
            ),
            lastWorkoutResult: ExerciseLog(
              exerciseId: 'face-pull',
              completedAt: DateTime(2026, 6, 16),
              weightKg: 12,
              reps: 16,
              rir: 2,
            ),
          ),
        ],
      ),
    ],
  ),
];
